authors: [tomjw64, HaydenCappadona]
name: HungerBarGames
description: Yet another Hunger Games plugin
version: 0.3
main: me.tomjw64.HungerBarGames.HungerBarGames
commands:
    hbg:
        usage: /<command> <args>
        description: HBG commands
softdepend: [Spout]

